import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {
  value: 0,
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const appSlice = createSlice({
  name: 'app',
  initialState:{
    channelID: null,
    channelName: null,
  },
  reducers: {
    setChanelID: (state, action) => {
        state.app += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const { setChanelID } = appSlice.actions;

export const selectChannelID = (state) => state.app.channelID;
export const selectChannelName = (state) => state.app.ChannelName;

export default appSlice.reducer;
